# Generated by Django 4.1.3 on 2022-12-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
